using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class NewBehaviourScript : MonoBehaviour
{
  [Header("Gradients")]
  [SerializeField] private Gradient fogGradient;
  [SerializeField] private Gradient ambientGradient;
  [SerializeField] private Gradient directionLightGradient;
  [SerializeField] private Gradient skyboxTintGradient;

  [Header("Enviromental Assets")]
  [SerializeField] private Light directionalLight;
  [SerializeField] private Material skyboxMaterial;

   [Header("Variables")]
   [SerializeField] private float dayDurationInSeconds = 60f;
   [SerializeField] private float rotationSpeed = 1f;

   private float currentTime = 0;

    private void Update()
    {
        UpdateTime();
        UpdateDayNightCycle();
        RotateSkybox(); 
    }

     private void UpdateTime()
     {
        currentTime += Time.deltaTime / dayDurationInSeconds;
        currentTime = Mathf.Repeat(currentTime, 1f);
    }

        private void UpdateDayNightCycle()
        {
            float sunPosition = Mathf.Repeat(currentTime + 0.25f,1f);
            directionalLight.transform.rotation = Quaternion.Euler(sunPosition*360f,0f,0f);

            RenderSettings.fogColor = fogGradient.Evaluate(currentTime);
            RenderSettings.ambientLight = ambientGradient.Evaluate(currentTime);

            directionalLight.color = directionLightGradient.Evaluate(currentTime);
            skyboxMaterial.SetColor("_Tint",skyboxTintGradient.Evaluate(currentTime));
        }

            private void RotateSkybox()
            {
                float currentRotation = skyboxMaterial.GetFloat("_Rotation");
                float newRotation = currentRotation + rotationSpeed * Time.deltaTime;
                skyboxMaterial.SetFloat("_Rotation",newRotation);
            }

            private void OnApplicationQuit()
            {
                skyboxMaterial.SetColor("_Tint",new Color(0.5f,0.5f,0.5f));
            }

            
        }
     






